/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author norton
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        decorateTableTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmptyListPanel = new javax.swing.JPanel();
        EmptyIconList = new javax.swing.JLabel();
        EmptyLabelText = new javax.swing.JLabel();
        EmptyNewTask = new javax.swing.JLabel();
        ToolBar = new javax.swing.JPanel();
        ToolBarTitle = new javax.swing.JLabel();
        ToolBarSubTitle = new javax.swing.JLabel();
        ProjectsPanel = new javax.swing.JPanel();
        ProjectTitle = new javax.swing.JLabel();
        ProjectIconsAdd = new javax.swing.JLabel();
        TaskPanel = new javax.swing.JPanel();
        TaskTitle = new javax.swing.JLabel();
        TaskIconAdd = new javax.swing.JLabel();
        ListProjectsPanel = new javax.swing.JPanel();
        ListProjectsItens = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelTaskTableGrid = new javax.swing.JTable();

        EmptyListPanel.setBackground(java.awt.Color.white);

        EmptyIconList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyIconList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        EmptyLabelText.setFont(new java.awt.Font("Nimbus Sans L", 1, 14)); // NOI18N
        EmptyLabelText.setForeground(new java.awt.Color(0, 153, 102));
        EmptyLabelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyLabelText.setText("Nenhuma tarefa por aqui");

        EmptyNewTask.setFont(new java.awt.Font("Nimbus Sans L", 0, 12)); // NOI18N
        EmptyNewTask.setForeground(new java.awt.Color(153, 153, 153));
        EmptyNewTask.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyNewTask.setText("Clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout EmptyListPanelLayout = new javax.swing.GroupLayout(EmptyListPanel);
        EmptyListPanel.setLayout(EmptyListPanelLayout);
        EmptyListPanelLayout.setHorizontalGroup(
            EmptyListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmptyListPanelLayout.createSequentialGroup()
                .addGroup(EmptyListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EmptyNewTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmptyLabelText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmptyIconList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        EmptyListPanelLayout.setVerticalGroup(
            EmptyListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmptyListPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(EmptyIconList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmptyLabelText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmptyNewTask)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        ToolBar.setBackground(new java.awt.Color(0, 153, 102));

        ToolBarTitle.setFont(new java.awt.Font("Nimbus Sans L", 1, 36)); // NOI18N
        ToolBarTitle.setForeground(java.awt.Color.white);
        ToolBarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        ToolBarTitle.setText(" Todo App");

        ToolBarSubTitle.setFont(new java.awt.Font("Nimbus Sans L", 0, 11)); // NOI18N
        ToolBarSubTitle.setForeground(java.awt.Color.white);
        ToolBarSubTitle.setText("Anote tudo não esqueça nada");

        javax.swing.GroupLayout ToolBarLayout = new javax.swing.GroupLayout(ToolBar);
        ToolBar.setLayout(ToolBarLayout);
        ToolBarLayout.setHorizontalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToolBarSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToolBarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ToolBarLayout.setVerticalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ToolBarTitle)
                .addGap(30, 30, 30)
                .addComponent(ToolBarSubTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProjectsPanel.setBackground(java.awt.Color.white);
        ProjectsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProjectTitle.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        ProjectTitle.setForeground(new java.awt.Color(0, 153, 102));
        ProjectTitle.setText("Projetos");

        ProjectIconsAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N

        javax.swing.GroupLayout ProjectsPanelLayout = new javax.swing.GroupLayout(ProjectsPanel);
        ProjectsPanel.setLayout(ProjectsPanelLayout);
        ProjectsPanelLayout.setHorizontalGroup(
            ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProjectIconsAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProjectsPanelLayout.setVerticalGroup(
            ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProjectIconsAdd)
                    .addComponent(ProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        TaskPanel.setBackground(java.awt.Color.white);
        TaskPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TaskTitle.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        TaskTitle.setForeground(new java.awt.Color(0, 153, 102));
        TaskTitle.setText("Tarefas");

        TaskIconAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N

        javax.swing.GroupLayout TaskPanelLayout = new javax.swing.GroupLayout(TaskPanel);
        TaskPanel.setLayout(TaskPanelLayout);
        TaskPanelLayout.setHorizontalGroup(
            TaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(TaskIconAdd)
                .addContainerGap())
        );
        TaskPanelLayout.setVerticalGroup(
            TaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(TaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaskIconAdd))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ListProjectsPanel.setBackground(java.awt.Color.white);
        ListProjectsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ListProjectsItens.setBackground(new java.awt.Color(255, 255, 255));

        jList1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList1.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFixedCellHeight(50);
        jList1.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jList1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ListProjectsItens.setViewportView(jList1);

        javax.swing.GroupLayout ListProjectsPanelLayout = new javax.swing.GroupLayout(ListProjectsPanel);
        ListProjectsPanel.setLayout(ListProjectsPanelLayout);
        ListProjectsPanelLayout.setHorizontalGroup(
            ListProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListProjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListProjectsItens)
                .addContainerGap())
        );
        ListProjectsPanelLayout.setVerticalGroup(
            ListProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListProjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListProjectsItens, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelTaskTableGrid.setFont(new java.awt.Font("Nimbus Sans L", 0, 14)); // NOI18N
        jPanelTaskTableGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jPanelTaskTableGrid.setGridColor(java.awt.Color.lightGray);
        jPanelTaskTableGrid.setRowHeight(40);
        jPanelTaskTableGrid.setSelectionBackground(new java.awt.Color(0, 255, 102));
        jPanelTaskTableGrid.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jPanelTaskTableGrid);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProjectsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListProjectsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListProjectsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
        
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel EmptyIconList;
    javax.swing.JLabel EmptyLabelText;
    javax.swing.JPanel EmptyListPanel;
    javax.swing.JLabel EmptyNewTask;
    javax.swing.JScrollPane ListProjectsItens;
    javax.swing.JPanel ListProjectsPanel;
    javax.swing.JLabel ProjectIconsAdd;
    javax.swing.JLabel ProjectTitle;
    javax.swing.JPanel ProjectsPanel;
    javax.swing.JLabel TaskIconAdd;
    javax.swing.JPanel TaskPanel;
    javax.swing.JLabel TaskTitle;
    javax.swing.JPanel ToolBar;
    javax.swing.JLabel ToolBarSubTitle;
    javax.swing.JLabel ToolBarTitle;
    javax.swing.JList<String> jList1;
    javax.swing.JPanel jPanel5;
    javax.swing.JTable jPanelTaskTableGrid;
    javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTask(){
        
        //Customizando o Header da tabela Task
        jPanelTaskTableGrid.getTableHeader().setFont(new Font("Nimbus Sans L", Font.BOLD, 14));
        jPanelTaskTableGrid.getTableHeader().setBackground(new Color(0, 153, 102));
        jPanelTaskTableGrid.getTableHeader().setForeground(new Color(255, 255, 255));
        
        //Sort automatizado das colunas
        jPanelTaskTableGrid.setAutoCreateRowSorter(true);
    }
    
}



